module.exports = {
	production: [
		"cover 99% in US and > 0.1% in US",
		"last 5 and_chr major versions and > 0.1% in US",
		"last 5 and_ff major versions and > 0.1% in US",
		"last 5 ios_saf major versions and > 0.1% in US",
		"last 5 op_mini major versions and > 0.1% in US",
		"last 5 samsung major versions and > 0.1% in US",
		"last 5 android major versions and > 0.1% in US",
		"not dead",
	],
	local: [
		"last 2 Chrome versions",
		"unreleased Chrome versions",
		"last 2 Firefox versions",
		"unreleased Firefox versions",
		"last 2 and_chr major versions",
		"last 2 and_ff major versions",
		"last 2 ios_saf major versions",
		"last 2 android major versions",
		"last 2 op_mini major versions",
		"last 2 samsung major versions",
		"not dead",
	],
};
