#!/bin/bash

set -o pipefail
set -exu

SCHEMA="${TMPDIR}tsconfig-schema.json"

cd "$(dirname "$0")/.."
wget https://json.schemastore.org/tsconfig -O "$SCHEMA"
node ./genTsconfig.js | while read LINE
	do
		npm run ajv -- -s "$SCHEMA" -d "$LINE"
	done
