---

extends:
  - 'eslint:recommended'
  - "plugin:lodash/recommended"
  - "plugin:promise/recommended"
  - 'plugin:regexp/recommended'
  - airbnb-base
  - problems
plugins:
  - lodash
  - promise
  - regexp
