name: Prettier

on:
  pull_request:
    - opened
    - reopened
    - synchronized
    - ready_for_review
  create:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - run: npx prettier --write .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Prettier formatting
