---

# This works to guarantee that master and development stay in sync by
# automatically creating PRs between them when they get out of sync.

name: Sync master and development
on:
  push:
    branches:
      - master
      - development

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Creating PR from master to development
        id: master-to-development
        uses: tretuna/sync-branches@1.2.0
        with:
          PULL_REQUEST_TITLE: "Master is ahead of development!!!!!11one!1!!1!!!"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: master
          TO_BRANCH: development
      - name: Creating PR from development to master
        id: development-to-master
        uses: tretuna/sync-branches@1.2.0
        with:
          PULL_REQUEST_TITLE: "Release PR"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: development
          TO_BRANCH: master
          PULL_REQUEST_IS_DRAFT: true
