---

extends:
  - "@k4connect"
  - "airbnb-typescript/base"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
parserOptions:
  project: './tsconfig.json'
plugins:
  - "@typescript-eslint"
rules:
  # Stylistic things are handled by Prettier.
  indent: "off"
  "@typescript-eslint/indent": "off"
  max-len: "off"
  "@typescript-eslint/semi": "off"
  "@typescript-eslint/comma-spacing": "off"
